POST {{url_prefix}}/expressOrder/insert
Content-Type: application/json

{
  "items": [
    {
      "product": {
        "id": 1
      },
      "quantity": 4
    },
    {
      "product": {
        "id": 2
      },
      "quantity": 7
    }
  ]
}

###

PUT {{url_prefix}}/expressOrder/deliver?id=xxx&expressNumber=xxx&expressCompany=xxx
Accept: application/json

###

GET {{url_prefix}}/expressOrder/findAll
Accept: application/json

###

PUT {{url_prefix}}/expressOrder/receive
Content-Type: application/json

{
  "id": 7,
  "createTime": "2022-01-13 21:08:44",
  "updateTime": "2022-01-13 23:03:59",
  "expressCompany": "SF",
  "expressNumber": "786547654",
  "status": "DELIVERED",
  "deliverer": {
    "id": 36,
    "createTime": "2022-01-13 17:30:59",
    "updateTime": "2022-01-13 17:30:59",
    "username": "18570771840",
    "password": "$2a$10$3XpaYYJogsTpb0kV2ihBAOgbQzhpzshZN4DHyXrRPU1mNZNB8sMTO",
    "name": "王五",
    "role": "WAREHOUSE_KEEPER",
    "phoneNumber": null
  },
  "receiver": null,
  "items": [
    {
      "id": 9,
      "createTime": "2022-01-13 21:08:44",
      "updateTime": "2022-01-13 21:08:44",
      "product": {
        "id": 2,
        "createTime": "2022-01-13 12:54:28",
        "updateTime": "2022-01-13 12:54:28",
        "name": "清风牌面巾纸",
        "barcode": "6922266446726",
        "brand": "清风",
        "specification": "150抽/包",
        "inventory": {
          "id": 2,
          "createTime": "2022-01-13 12:54:28",
          "updateTime": "2022-01-13 23:03:59",
          "warehouseInventory": 5,
          "hubInventory": 10,
          "midwayInventory": 5
        },
        "remark": null,
        "price": 300,
        "customsInfo": {
          "id": 2,
          "createTime": "2022-01-13 12:54:28",
          "updateTime": "2022-01-13 12:54:28",
          "hsCode": "42022900",
          "materialBeschaffenheit": "This version is in a nano size in classic calfskin.Shoulder, crossbody, top handle or clutch carry. Detachable chain. shoulder strap. Zip closure with calfskin pull. Customisable with strap and personalised charms. Herringbone cotton canvas lining Embossed Anagram",
          "brandArticleNo": "A510U98X01",
          "brand": "LOEWE",
          "articleName": "Nano Puzzle bag in classic calfskin",
          "unitPrice": 54096
        }
      },
      "quantity": 5,
      "receivedQuantity": 5
    },
    {
      "id": 10,
      "createTime": "2022-01-13 21:08:44",
      "updateTime": "2022-01-13 21:08:44",
      "product": {
        "id": 6,
        "createTime": "2022-01-13 12:54:30",
        "updateTime": "2022-01-13 12:54:30",
        "name": "一次性使用医用口罩",
        "barcode": "6959385755583",
        "brand": "振德",
        "specification": "10只装",
        "inventory": {
          "id": 6,
          "createTime": "2022-01-13 12:54:30",
          "updateTime": "2022-01-13 23:03:59",
          "warehouseInventory": 5,
          "hubInventory": 10,
          "midwayInventory": 5
        },
        "remark": null,
        "price": 250,
        "customsInfo": {
          "id": 6,
          "createTime": "2022-01-13 12:54:30",
          "updateTime": "2022-01-13 12:54:30",
          "hsCode": "42033000",
          "materialBeschaffenheit": "Schwarzes Leder.Glänzende, goldfarbene Metallteile.GG Schnalle.Hergestellt in Italien.Kann als Hüft- oder Taillengürtel getragen werden. Die Größen variieren je nachdem, wo der Gürtel getragen wird. Bitte sehen Sie im Größenratgeber nach, um Ihre Größe zu finden.",
          "brandArticleNo": "406831 0YA0G 1000",
          "brand": "GUCCI",
          "articleName": "GG Marmont Gürtel aus Leder mit glänzender Schnalle",
          "unitPrice": 31149
        }
      },
      "quantity": 5,
      "receivedQuantity": 5
    }
  ]
}

###

GET https://wuliu.market.alicloudapi.com/kdi?no=462180863832770
Authorization: APPCODE bb3a46095c8647c3a7cf1f934e1e8b14